excluded:
  - Pods
  - WalkJourney/AppDelegate.swift
  - WalkJourney/SceneDelegate.swift
  
disabled_rules:
  - trailing_whitespace
  - function_parameter_count
  
identifier_name:
 min_length: 2
 max_length:
    warning: 40
    error: 50
    
 excluded: # excluded via string array
    - id
    - URL
    - url
    - app
    
file_length:
  warning: 500
  error: 800
  
type_body_length:
  - 500 # warning
  - 700 # error
  
opt_in_rules:
  - force_unwrapping
  
large_tuple:
  - 3
  
